### ISSUE TITLE
erreur 500 : Internal Server Error

### ISSUE THREAD

**Issue by BaptisteVachon** [CaraGk/pigass#33]
C'est ici qu'on te pose des questions quand le site ne fonctionne pas ? :)
Une fois connecté, je n'ai accès ni à mon profil, ni à mes adhésions, il n'y a qu'une phrase affichée : "Le serveur a retourné une erreur "500 Internal Server Error"." et je ne peux faire qu'une action : me déconnecter.
Baptiste

**Comment by CaraGk** [comment]
Apparemment, j'avais un bug pour les adhésions incomplètes sans adhésion antérieure, ce qui peut correspondre à ton cas.

Tu me diras si la mise à jour corrige ton problème.

**Comment by CaraGk** [comment]
En fait bug lié à la redirection vers une question complémentaire à répondre associée à la recherche d'une adhésion active n'existant pas (getCurrentForPerson).
